#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
out=${1:-"$root/docs"}
mkdir -p "$out/api"
cd "$root"

go run ./cmd/xep-matrix > "$out/xep-support.md"

write_api() {
    package=$1
    target=$2
    title=$3
    {
        printf '# %s API reference\n\n' "$title"
        printf 'Generated by `scripts/generate-docs.sh` from exported Go documentation.\n\n'
        printf '```text\n'
        go doc -all "$package"
        printf '```\n'
    } > "$out/api/$target.md"
}

write_api ./xmpp xmpp xmpp
write_api ./xep xep xep
write_api ./omemo omemo omemo
write_api ./omemo/testkit omemo-testkit 'omemo/testkit'
